# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-11 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_no', models.IntegerField()),
                ('marks', models.IntegerField()),
                ('negative', models.IntegerField()),
                ('correct_ans', models.IntegerField()),
                ('received_option', models.CharField(max_length=6)),
                ('no_of_que_attempt', models.IntegerField()),
                ('no_of_correct_ans', models.IntegerField()),
                ('no_of_wrong_ans', models.IntegerField()),
            ],
        ),
    ]
