# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-11 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0002_remove_quiz_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='url',
            field=models.SlugField(default='test-test', help_text='a user friendly url', max_length=60, verbose_name='user friendly url'),
        ),
    ]
