# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-10 21:41
from __future__ import unicode_literals

from django.db import migrations, models
import upload.models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to=upload.models.upload_location),
        ),
    ]
